export const FETCH_USER = 'fetch_user'
export const FETCH_USER_ERROR = 'fetch_user_error'
export const FETCH_DATA = 'fetch_data'
export const FETCH_DATA_ERROR = 'fetch_data_error'
export const CREATE_MEDIA_SCRAPER = 'create_media_scraper'
export const CREATE_MEDIA_SCRAPER_ERROR = 'create_media_scraper_error'
